import { Injectable } from '@angular/core';
import {map, Observable, of, timer} from 'rxjs';
import {HttpClient} from '@angular/common/http';

// will be generated by swagger...
export interface TodoDTO {
  id: number;
  descr: string;
}

@Injectable({
  providedIn: 'root',
})
export class TodoService {

  constructor(private httpClient: HttpClient) {}

  callHttpCreateTodo(descr: string): Observable<TodoDTO> {
    return this.httpClient.post<TodoDTO>('/api/todo', { descr });
  }

  mockCallHttpCreateTodo(description: string): Observable<string> {
    return timer(5_000).pipe(map(x => "ok"));
  }

}
